import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LeftSide from "@/layout/LeftSide";
import Header from "@/layout/Header";
import Player from "@/layout/Player";
import RightSide from "@/layout/RightSide";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='wrap'>
          <div className='flex flex-row'>
            <LeftSide />
            <div className='section'>
              <Header />
              {children}
            </div>
            <RightSide />
          </div>
          <Player />
        </div>

      </body>
    </html>
  );
}
